lib/facebook/messenger/server.rb

I think this would be more friendly for threaded
servers. I don't think request/response data should
be shared.

Use instance variables for request/response data.

---

README.md

I think there is a typo in the readme which confused me for a while

fix typo in readme which incorrectly includes the production environment

---

lib/facebook/messenger/bot.rb

klass is not a Class-like object, it's an instance of one of the incoming message classes. I couldn't find a better name than the ones used in the Messenger Platform documentation.
Naming is hard.

Rename klass variable to callback

---

lib/facebook/messenger/incoming/delivery.rb
lib/facebook/messenger/incoming/message.rb
lib/facebook/messenger/incoming/optin.rb
lib/facebook/messenger/incoming/postback.rb
spec/facebook/messenger/incoming/delivery_spec.rb
spec/facebook/messenger/incoming/message_spec.rb
spec/facebook/messenger/incoming/optin_spec.rb
spec/facebook/messenger/incoming/postback_spec.rb

Hello friends!
In order to process messages asynchronously, I want to store their `payload` in a queue. In this PR, I make the `@payload` instance variable public.
It however conflicts with the existing `Postback#payload` method.
How would you like to go about that?
1. Rename `@payload` to `@raw_payload` ?
2. Rename `Postback#payload` to `Postback#fb_payload`?
3. ... ?

Make incomings payloads public

---

lib/facebook/messenger/bot.rb
lib/facebook/messenger/incoming.rb
lib/facebook/messenger/incoming/read.rb
spec/facebook/messenger/bot_spec.rb

I have no idea why this started happening, but Facebook started sending me `messaging` payloads that look like this:
```
{"sender"=>{...}, "recipient"=>{...}, "timestamp"=>1465354035944, "read"=>{"watermark"=>1465354034142, "seq"=>33}}
```
which raises an `UnknownPayload` and breaks my app 😱. This behaviour doesn't appear to be documented by Facebook yet.
This PR adds support for this new type of payload.

Add read receipt message type

---

README.md
lib/facebook/messenger.rb
lib/facebook/messenger/thread.rb
spec/facebook/messenger/thread_spec.rb

Facebook added thread settings which are the new way to set the welcome message, the greeting text and the new persistent menu feature.
Let me know if I implemented it the right way or if there's anything to change.
See:
https://developers.facebook.com/docs/messenger-platform/thread-settings/
https://developers.facebook.com/docs/messenger-platform/changelog#20160630
http://messengerblog.com/bots/messenger-platform-1-1-ratings-quick-replies-account-linking-and-more/
Related #50

Add thread settings

---

lib/facebook/messenger/bot.rb
spec/facebook/messenger/incoming/read_spec.rb
spec/facebook/messenger/incoming_spec.rb

The changes in #41 were supposed to add support to read payloads. But it actually never worked because read wasn't added to the list of events which can be passed to `Bot.on`. Doing `Bot.on :read` was generating the error `/gems/facebook-messenger-0.8.0/lib/facebook/messenger/bot.rb:34:in `on': read is not a valid event; available events are message,delivery,postback,optin (ArgumentError)`.
This pull request fixes it. It also adds more unit tests.

Read was never working

---

lib/facebook/messenger/bot.rb
lib/facebook/messenger/incoming.rb
lib/facebook/messenger/incoming/account_linking.rb
lib/facebook/messenger/incoming/message.rb
spec/facebook/messenger/bot_spec.rb
spec/facebook/messenger/incoming/account_linking_spec.rb
spec/facebook/messenger/incoming/message_spec.rb
spec/facebook/messenger/server_spec.rb

Added AccountLinking callback and fixed :read callback.

Added AccountLinking webhook support

---

README.md

Hi, 
I try to let Rails auto reload files in `app/bot` and I found `FileUpdateChecker` in [grape](https://github.com/ruby-grape/grape#reloading-in-rails-applications) README.
I update README to use same way to let bot files can reload by Rails without restart server.

Improve README for Rails to reload app/bot/**/*.rb files

---

lib/facebook/messenger/server.rb

events['entry'] may not always contain a message. I have been facing trouble with this thing and fixed it the following way. If I am missing anything here, please tell me.

Fix error when events does not contain a message

---

lib/facebook/messenger/incoming/postback.rb
spec/facebook/messenger/incoming/postback_spec.rb

Hi, so I ran into to an issue with postbacks and referrals. When there's no referral set from Facebook in the postback, the referral in the postback object returned another Referral object. 
This makes it hard to distinguish normal postbacks from m.me-referrals. Let me know, if i'm missing something.

Return nil when calling referral on postback when referral is not set

---

lib/facebook/messenger/incoming/common.rb
spec/facebook/messenger/incoming/common_spec.rb

Fixes #106 
Renamed `type` into `typing_on`
Added `typing_off` and `mark_seen` to comply with the sender API
https://developers.facebook.com/docs/messenger-platform/send-api-reference/sender-actions

Fix Sender-API

---

CHANGELOG.md

I was a little confused when checked the CHANGELOG and didn't find the `0.11.1` release since it was the current version of `facebook-messenger` on my app. I believe the CHANGELOG is outdated and this PR fixes it.

Update CHANGELOG for 0.11.1 version

---

README.md
Rakefile
lib/facebook/messenger.rb
lib/facebook/messenger/bot.rb
lib/facebook/messenger/profile.rb
spec/facebook/messenger/thread_spec.rb

Hello, I changed thread_settings to messenger_profile, due to deprecation in Send API 1.4, and especially introduction of nesting in Persistent menus.

Messenger profile

---

lib/facebook/messenger/incoming/message.rb
spec/facebook/messenger/incoming/message_spec.rb

Facebook Webhooks API now sends `
ID of the app from which the message was sent` as app_id in the payload.
Adding a method to fetch this id from payload.
More info: https://developers.facebook.com/docs/messenger-platform/webhook-reference/message-echo

Add method to fetch app_id in case of message echo

---

lib/facebook/messenger/incoming/message.rb
spec/facebook/messenger/incoming/message_spec.rb

Added helpers to access attachments, namely:
`image_attachment?`, `file_attachment?`, `location_attachment?` , `audio_attachment?`, `video_attachment?`, `fallback_attachment?` - to check the type of attachment.
`attachment_type` - to get the type of attachment present, eg 'file' or 'audio'
`attachment_url` - to get the url of the attachment present
`location_coordinates ` - to get the lat and long coordinates if the attachment type is location
@jgorset please advise on how to add tests for `location_coordinates` method. Do I need to create a new payload in the spec, because and image_attachment and location attachment won't be coming together in response.

Adding helpers for attachments

---

README.md

This fixed the syntax error caused by a single quote on the persistent menu example.

Fixing Syntax Error on Persistent Menu Example

---

lib/facebook/messenger/bot.rb
lib/facebook/messenger/profile.rb
lib/facebook/messenger/subscriptions.rb

There don't seem to be any messenger-related API changes from v2.6 to v2.9, but I have found that updating the version resolves the issue https://github.com/jgorset/facebook-messenger/issues/205 for me. Technically, we could update to v2.12 (the latest), but if you want to be conservative, I've split the difference and updated to 2.9 here.
The gem will have to update from v2.6 by July 2018 because that will be when v2.6 will no longer be available. Bumping to v2.9 will at least make sure the apis used by the gem are supported until July 2019.

update version of fb api to 2.9

---

lib/facebook/messenger/incoming/common.rb
spec/facebook/messenger/incoming/common_spec.rb

Per the [Facebook Checkbox Plugin Docs](https://developers.facebook.com/docs/messenger-platform/discovery/checkbox-plugin)
> 7. Handle the user response
> If the user responds to your message, the appropriate event (messages, messaging_postbacks, etc.) will be sent to your webhook, with a prior_message object appended. The prior_message object includes the source of the message the user is responding to, as well as the user_ref used for the original message send.
Adding that `prior_message` method to the `Facebook::Messenger::Incoming::Common` module for easy access to that messaging info, if available.

Add prior_message to Incoming::Common

---

README.md

According to [Messaging types documentation](https://developers.facebook.com/docs/messenger-platform/send-messages/#messaging_types) it's not `message_type` but `messaging_type`

Fix typo for messaging types in README

---

lib/facebook/messenger/incoming/referral.rb

I just added the following to the class Facebook::Messenger::Incoming::Referral::Referral:
```
def ad_id
@referral['ad_id'] if @referral.key?('ad_id')
end
```
Is to have access to the ad_id when the ad_source is ADS

Add ad_id field to referral nested class

---

lib/facebook/messenger/subscriptions.rb
spec/facebook/messenger/subscriptions_spec.rb

Facebooks Api can't handle an empty array in the query params resulting in a 500:
```
19:53:50 web.1  | <- "POST /v3.2/me/subscribed_apps?access_token=XXX&subscribed_fields[]= HTTP/1.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAccept: */*\r\nUser-Agent: Ruby\r\nConnection: close\r\nHost: grap
h.facebook.com\r\nContent-Length: 0\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n"
19:53:50 web.1  | <- ""
19:53:50 web.1  | -> "HTTP/1.1 500 Internal Server Error\r\n"
19:53:50 web.1  | -> "x-page-usage: {\"call_count\":2,\"total_cputime\":1,\"total_time\":1}\r\n"
19:53:50 web.1  | -> "x-app-usage: {\"call_count\":0,\"total_cputime\":0,\"total_time\":0}\r\n"
19:53:50 web.1  | -> "WWW-Authenticate: OAuth \"Facebook Platform\" \"unknown_error\" \"An unknown error has …
```

Fix: Subscriptions with empty subscribed_fields results in 500
