README.md, examples/bot.rb, examples/config.ru, facebook-messenger.gemspec, lib/facebook/messenger.rb, lib/facebook/messenger/bot.rb, lib/facebook/messenger/configuration.rb, lib/facebook/messenger/message.rb, lib/facebook/messenger/server.rb, spec/facebook/messenger/bot_spec.rb, spec/facebook/messenger/message_spec.rb, spec/facebook/messenger/server_spec.rb
=> Receive messages

lib/facebook/messenger/bot.rb
ref: #9 
(PD: Actually, it doesn't fix the issue but at least will show the warning)
=> Access hooks via the reader method.

lib/facebook/messenger/server.rb
Looks like they're going to be deprecated in Rack 2.0 (https://github.com/rack/rack/pull/1069/files)
=> Use Rack::Request#params instead of #[]

README.md
=> Add note about testing your locally running bot

README.md, lib/facebook/messenger/incoming/message.rb, spec/facebook/messenger/incoming/message_spec.rb
Useful when need to check for images / geo coordinates received
=> Make attachments available for messenger received

README.md, lib/facebook/messenger.rb, lib/facebook/messenger/welcome.rb, spec/facebook/messenger/welcome_spec.rb
=> Implement welcome messages

lib/facebook/messenger/incoming/message.rb, spec/facebook/messenger/incoming/message_spec.rb
Add other incoming classes have a recipient method, so I added one for message.
=> Add recipient method to incoming message

facebook-messenger.gemspec, lib/facebook/messenger/concerns/default_options.rb, lib/facebook/messenger/incoming.rb, lib/facebook/messenger/incoming/optin.rb, lib/facebook/messenger/incoming/postback.rb
Just a little bit drying to improve Code Climate rating
=> Slight refactoring to increase code climate

README.md
=> unify directory name on Rails; bot -> bots

README.md
caused an error when I used it - this works!
=> fixed typo in rails example

lib/facebook/messenger/incoming/message.rb, spec/facebook/messenger/incoming/message_spec.rb
=> Add echo status to message

.rubocop.yml, Rakefile, facebook-messenger.gemspec, lib/facebook/messenger/bot.rb
=> Fix rubocop

README.md
=> Refer to Facebook's documentation to create an application

lib/facebook/messenger/bot.rb
=> Timeout after 300 seconds (up from 60)

facebook-messenger.gemspec
=> Support rack >= 1.4.5

README.md
=> Fix documentation for ConfigurationProvider#access_token_for

lib/facebook/messenger/incoming/optin.rb, spec/facebook/messenger/incoming/optin_spec.rb
This makes it easier to work with the Checkbox plugin (https://developers.facebook.com/docs/messenger-platform/plugin-reference/checkbox-plugin).
=> Add user_ref method to optin messages

README.md, lib/facebook/messenger/incoming.rb, lib/facebook/messenger/incoming/message_request.rb, spec/facebook/messenger/incoming/message_request_spec.rb
=> Support message request webhook events not sent via optin

lib/facebook/messenger/bot/message_type.rb, spec/facebook/messenger/bot_spec.rb
fix rubocop errors introduced in #186
=> fix rubocop errors introduced in #186

README.md, lib/facebook/messenger.rb, lib/facebook/messenger/server_no_error.rb, spec/facebook/messenger/server_no_error_spec.rb
=> Implement ServerNoError

lib/facebook/messenger.rb, lib/facebook/messenger/bot.rb, lib/facebook/messenger/configuration.rb, lib/facebook/messenger/configuration/providers/base.rb, lib/facebook/messenger/configuration/providers/environment.rb, lib/facebook/messenger/error.rb, lib/facebook/messenger/incoming.rb, lib/facebook/messenger/incoming/account_linking.rb, lib/facebook/messenger/incoming/common.rb, lib/facebook/messenger/incoming/delivery.rb, lib/facebook/messenger/incoming/message.rb, lib/facebook/messenger/incoming/message_echo.rb, lib/facebook/messenger/incoming/optin.rb, lib/facebook/messenger/incoming/payment.rb, lib/facebook/messenger/incoming/postback.rb, lib/facebook/messenger/incoming/read.rb, lib/facebook/messenger/incoming/referral.rb, lib/facebook/messenger/profile.rb, lib/facebook/messenger/server.rb, lib/facebook/messenger/subscriptions.rb, lib/facebook/messenger/version.rb
I have added some code documentation according to yard standards.
=> Added Code documentation

README.md
Added the documentation coverage badge.
=> Documentation coverage badge.

README.md
Removed old references to hyperoslo
=> Removed old references to hyperoslo

lib/facebook/messenger/bot.rb
I forgot to include the new constants in the main file
=> Add messaging type and tag

lib/facebook/messenger/profile.rb
Upgrades the profile API version to v3.2
Resolves #252
=> Updated profile to use v3.2

examples/bot.rb, lib/facebook/messenger/bot.rb, lib/facebook/messenger/incoming.rb, lib/facebook/messenger/incoming/message_reaction.rb, spec/facebook/messenger/bot_spec.rb, spec/facebook/messenger/incoming/message_reaction_spec.rb
```ruby
Bot.on :reaction do |message|
message.emoji # => "👍"
message.action # => "react"
message.reaction # => "like"
message.reply(text: 'Thanks for liking my message!')
end
```
=> Added `reaction` event
